# Netlify configuration file for MindEase React SPA

[build]
  # Build command
  command = "npm run build"
  # Directory to publish (Vite builds to 'dist' by default)
  publish = "dist"

# SPA redirect rules - handles client-side routing
[[redirects]]
  # Redirect all routes to index.html for React Router to handle
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for better performance and security
[[headers]]
  for = "/*"
  [headers.values]
    # Cache static assets
    Cache-Control = "public, max-age=31536000"
    # Security headers
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/index.html"
  [headers.values]
    # Don't cache the main HTML file
    Cache-Control = "public, max-age=0, must-revalidate"

# Optional: Custom error pages
[[redirects]]
  from = "/404"
  to = "/index.html"
  status = 200